### ISSUE TITLE
create metadata-extractor executable

### ISSUE THREAD

**Issue by abma** [springlobby/lsl#4]
extract --unitsync=/path/to/unitsync --outputdir=/path/to/output --file=/path/to/file1 --file=/path/to/file2 

parameters:

-mapinfo (=metal/map/.. data, mapoptions)
-gameimages
-gamedate
... see upq from springfiles

**Comment by abma** [comment]
the tool exists, now it should replace the upq job:

https://github.com/springfiles/upq/blob/master/jobs/extract_metadata.py

**Comment by abma** [comment]
todo:
- merge json cache files into a single file
- check if all needed data is extracted
- ... ?

**Comment by db81** [comment]
What if that functionality was built into spring itself? Seems easier that way, less code duplication, no extra work required for distribution.

**Comment by abma** [comment]
thats meant with "integrate into spring static builds"

**Comment by abma** [comment]
* add a smart way to communicate between springlobby + the tool

thats basicly done, http / json will be used

**Comment by abma** [comment]
moved to https://github.com/spring/pr-downloader/issues/90
